# Generated by Django 2.0.2 on 2018-04-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='learningpost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500, unique=True)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('date', models.DateTimeField()),
                ('body', models.TextField()),
                ('links', models.URLField(blank=True, max_length=500)),
                ('website', models.URLField(blank=True, max_length=250)),
            ],
        ),
    ]
