# Generated by Django 2.0.2 on 2018-04-25 19:06

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningpage', '0002_auto_20180426_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpost',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
