# Generated by Django 2.0.2 on 2018-04-25 20:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningpage', '0003_auto_20180426_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpost',
            name='headline',
            field=ckeditor.fields.RichTextField(unique=True),
        ),
    ]
