# Generated by Django 2.0.2 on 2018-04-26 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningpage', '0004_auto_20180426_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpost',
            name='Topic',
            field=models.CharField(default='somevalue', max_length=500, unique=True),
        ),
    ]
