# Generated by Django 2.0.2 on 2018-04-26 06:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningpage', '0005_learningpost_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningpost',
            name='Topic',
            field=ckeditor.fields.RichTextField(default='somevalue', max_length=500, unique=True),
        ),
    ]
