# Generated by Django 2.0.2 on 2018-04-26 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learningpage', '0006_auto_20180426_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningpost',
            name='Topic',
        ),
    ]
