# Generated by Django 2.0.2 on 2018-04-26 06:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learningpage', '0007_remove_learningpost_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningpost',
            name='Topic',
            field=models.TextField(default='Here put the topic of your post this is only for the Database entry', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='learningpost',
            name='headline',
            field=ckeditor.fields.RichTextField(default='Here put the Headline of your post', max_length=500, unique=True),
        ),
    ]
